### ISSUE TITLE
User Authentication error

### ISSUE THREAD

**Issue by JoeChaiet** [infusionsoft/infusionsoft-php#101]
When I try to authenticate a user using `$infusionsoft->data()->authenticateUser('joe@example', 'password');` I get:
`Fatal error: Uncaught exception 'Infusionsoft\Http\HttpException' with message 'exception 'fXmlRpc\Exception\FaultException' with message '[FailedLoginAttempt]Invalid username and/or password.' in /vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/FaultException.php:32 Stack trace: #0 /vendor/lstrojny/fxmlrpc/src/fXmlRpc/Parser/XmlReaderParser.php(373): fXmlRpc\Exception\FaultException::fault(Array) #1 /vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(153): fXmlRpc\Parser\XmlReaderParser->parse('<?xml version="...') #2 /vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php(28): fXmlRpc\Client->call('DataService.aut...', Array) #3 /vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php(404): Infusionsoft\Http\InfusionsoftSerializer->request('DataSer in /vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php on line 34`

My credentials are correct, they are set to what I use to sign into my Infusionsoft app. Another app that uses the php-isdk works with no issue using isdk authenticateUser, which requires the same credentials.

What am I doing wrong?

**Comment by JoeChaiet** [comment]
Nevermind.

**Comment by JoeChaiet** [comment]
nevermind. figured it out. syntax was slightly off.
