### ISSUE TITLE
Error in fetching paymentOption in invoice api

### ISSUE THREAD

**Issue by akprgm** [infusionsoft/infusionsoft-php#157]
I am trying to fetch paymentOptions in infusionsoft account but i am getting an error for a specific client. For all other client it's working fine. Can anyone tell what could be the possible cause of error

Stack Trace:
#0 /home/forge/hook.linkleads.io/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Parser/XmlReaderParser.php(116): fXmlRpc\Exception\RuntimeException::unexpectedTag('name', 256, Array, 6, '<name/>')
#1 /home/forge/hook.linkleads.io/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(157): fXmlRpc\Parser\XmlReaderParser->parse('<?xml version="...', false)
#2 /home/forge/hook.linkleads.io/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php(28): fXmlRpc\Client->call('InvoiceService....', Array)
#3 /home/forge/hook.linkleads.io/vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php(384): Infusionsoft\Http\InfusionsoftSerializer->request('https://api.inf...', 'InvoiceService....', Array, Object(fXmlRpc\Client))
#4 /home/forge/hook.linkleads.io/vendor/infusionsoft/php-sdk/src/Infusionsoft/Api/InvoiceService.php(153): Infusionsoft\Infusionsoft->request('InvoiceService....')

Call Site look like this:-
$this->infusionsoft->invoices()->getAllPaymentOptions();

**Comment by akprgm** [comment]
If any other guy facing this problem, i found the solution.

Actually the issue was in account, payment options stored in infusionsoft were like this.
...........................
: Check               :
: CreaditCard     :
:                          :
: Paypal              :
:.........................:

Notice the space between creaditcard and paypal, unlikely infusionsoft sdk was not able to handle this.
