### ISSUE TITLE
Random failure to refresh OAuth token.

### ISSUE THREAD

**Issue by ellisio** [infusionsoft/infusionsoft-php#220]
This has been happening for a little over a year. We have made requests to Fairchild, who has directed us to community forums and other forms of support without giving us any real indication on what is actually happening.

We are deeply integrated with the Infusionsoft SDK for our company (Salesmsg). In the screenshot below, you will see that we are running a Laravel Artisan command that simply attempts to refresh the access token, nothing more.

Randomly it will fail, and randomly it will pass. This happens almost daily for us. Due to this behavior, our clients who are connected to our Infusionsoft integration, get disconnected.

While I would like to say we can fix this by "hoping" the disconnect was a false positive and just try again, we can't confidently go about this approach. The failures could happen several times in a row, or once, before we get a success. Therefore, I don't want to keep looping until we get a success, because this could lead to all kinds of problems.

To me, this sounds like the OAuth vendor Infusionsoft is using is experiencing stability issues and returning a failed refresh, when in fact, the token is still valid.

I can see people have been having issues with refresh tokens dating back to 2015 with this SDK.

Has the dev team maintaining this SDK done any research into these claims? Is there any hope of salvation? We have extremely frustrated customers, which is frustrating us, as this instability is a real nightmare to deal with.

Here is a screenshot of this behavior:

![image](https://user-images.githubusercontent.com/127468/58351706-d6da5280-7e26-11e9-8a2a-daf71200c013.png)

The method in our Artisan command is:

```php
protected function refreshAccessToken()
{
    $config = Config::find('infusionsoft_token');

    if (! $config) {
        throw new Exception('Infusionsoft access token has been corrupted. Please re-authenticate.');
    }

    Infusionsoft::setToken(unserialize($config->value));

    $config->value = serialize(Infusionsoft::refreshAccessToken());
    $config->save();

    $this->info('Infusionsoft access token refresh.');
}
```

We are using the [`Infusionsoft`](https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/FrameworkSupport/Laravel/InfusionsoftFacade.php) facade to handle this.

**Comment by ROMzombie** [comment]
Hi @ellisio !  

When this particular question comes up usually it's due to using a web scripting framework that is doing two requests at once, creating a race condition where one puts in a request for a new token then the other thread does as well and invalidates the first token before it's received.  Since PHP is often used to handle several requests concurrently, the race condition is a not-uncommon side-effect of handling single-consumption tokens such as via the refresh.

**Comment by ellisio** [comment]
@ROMzombie while that may be true, this scenario is not that. From my screen shot those were ran synchronously, one by one, on a single server about one second apart.

Outside of that screen shot’s test case, this is our environment:

- `app1-us-c1b`
- `app2-us-c1b`

This refresh command is locked to `app1-us-c1b`. It runs once an hour. It is never ran on the second server as we restrict the command to hostname.

Above, we ran this in an off hour window; therefore there was zero chance this was ran in a collision window with that command. I would also like to note that our server to server key is only used by this refresh command.

When these errors occurred, this was when we had several customers complaining via Intercom that they got disconnected. Each customer has a unique token per their account. Therefore the refresh is unique per customer request. 

So, this is what is having us question the provider’s stability for Infusionsoft.

We discussed this issue with Fairchild at ICON in 2017. We were directed to public forums for help; even though we were and event sponsor. We have since been stonewalled with any technical support requests.

Quite frankly, this is beyond frustrating from a developer stance. Our frustrations are amplified by our customer complaints. 

We want to resolve this for our customers, but we can’t do that without help from Infusionsoft.

**Comment by larsenkevin** [comment]
I've had multiple reports of refresh failing also. It was working very reliably for my add-on for years but just recently started failing randomly.

**Comment by bbooth** [comment]
@ellisio can you get me the response headers as well as the request bodies and headers (minus any sensitive information)?

**Comment by ellisio** [comment]
@bbooth We are deploying a code change now to capture these specific failures which should include this information. As soon as we capture one, I will post it here.

**Comment by ellisio** [comment]
@bbooth Okay, so after watching our logging we are only getting the stack trace (like my screenshot in the OP). This is because of [`InufisonsoftSerializer:34`](https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/Http/InfusionsoftSerializer.php#L34).

From here, it drills into `fXmlRpc`'s library, which would need to be modified to send the response headers back with the exception.

The most I can give you at this time would be all the timestamps of when this occurred on our production instances. If you look at the [log dump](https://gist.github.com/ellisio/21ebc7fa802695b5c66cafdc7e4899be) from the last 30 days we are noticing this behavior happens on 15 minute markers, or very close to, a few times a day.

Is there a background process running on Infusionsoft, or the vendor, on 15 minute intervals that could be causing this as a side effect?

What is even more confusing about this is that the errors we are logging only happen on `queue1-us-c1b`. You will see in my OP that I was running those commands on `app1-us-c1b`. The reason those logs _did not_ show up in our log export is because that was in Laravel's Artisan Tinker command, and that particular log output is piped to /dev/null on Production so a debugging developer doesn't trigger alerts.

After poking around, we have also concluded that the only CRON running on a 15 minute interval on our end runs on `app1-us-c1b` solely, and only talks to our Redis instance. So it isn't a factor in this situation.

Example stack trace:
```
fXmlRpc\Exception\HttpException: An HTTP error occurred: Unauthorized in /var/www/app/releases/20190603161859/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/HttpException.php:32
Stack trace:
#0 /var/www/app/releases/20190603161859/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Transport/HttpAdapterTransport.php(65): fXmlRpc\Exception\HttpException::httpError('Unauthorized', 401)
#1 /var/www/app/releases/20190603161859/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(154): fXmlRpc\Transport\HttpAdapterTransport->send('https://api.inf...', '<?xml version="...')
#2 /var/www/app/releases/20190603161859/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php(28): fXmlRpc\Client->call('ContactService....', Array)
#3 /var/www/app/releases/20190603161859/vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php(456): Infusionsoft\Http\InfusionsoftSerializer->request('ContactService....', 'https://api.inf...', Array, Object(fXmlRpc\Client))
#4 /var/www/app/releases/20190603161859/vendor/infusionsoft/php-sdk/src/Infusionsoft/Api/ContactService.php(73): Infusionsoft\Infusionsoft->request('ContactService....', '446523', Array)
#5 /var/www/app/releases/20190603161859/app/Integrations/Drivers/Infusionsoft.php(135): Infusionsoft\Api\ContactService->load('446523', Array)
#6 /var/www/app/releases/20190603161859/app/Integrations/Integration.php(331): App\Integrations\Drivers\Infusionsoft->App\Integrations\Drivers\{closure}()
#7 /var/www/app/releases/20190603161859/app/Integrations/Drivers/Infusionsoft.php(136): App\Integrations\Integration->try(Object(Closure))
#8 /var/www/app/releases/20190603161859/app/Triggers/Jobs/Infusionsoft/InfusionsoftSendTrigger.php(79): App\Integrations\Drivers\Infusionsoft->getContactDetails('446523')
#9 /var/www/app/releases/20190603161859/app/Triggers/Jobs/Infusionsoft/InfusionsoftSendTrigger.php(52): App\Triggers\Jobs\Infusionsoft\InfusionsoftSendTrigger->getContactDetailsForTrigger(Object(App\Triggers\Trigger), Object(Illuminate\Support\Collection))
#10 /var/www/app/releases/20190603161859/app/Triggers/Jobs/SendTrigger.php(158): App\Triggers\Jobs\Infusionsoft\InfusionsoftSendTrigger->mapContactDetails(Object(App\Triggers\Trigger), Object(Illuminate\Support\Collection))
#11 /var/www/app/releases/20190603161859/app/Triggers/Jobs/SendTrigger.php(129): App\Triggers\Jobs\SendTrigger->getContact(Object(App\Webhooks\Webhook), Object(Illuminate\Support\Collection))
#12 /var/www/app/releases/20190603161859/app/Triggers/Jobs/SendTrigger.php(117): App\Triggers\Jobs\SendTrigger->process()
#13 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiter.php(90): App\Triggers\Jobs\SendTrigger->App\Triggers\Jobs\{closure}()
#14 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiterBuilder.php(113): Illuminate\Redis\Limiters\DurationLimiter->block(3, Object(Closure))
#15 /var/www/app/releases/20190603161859/app/Triggers/Jobs/SendTrigger.php(120): Illuminate\Redis\Limiters\DurationLimiterBuilder->then(Object(Closure), Object(Closure))
#16 [internal function]: App\Triggers\Jobs\SendTrigger->handle(Object(App\Contacts\Repositories\ContactRepository), Object(App\Conversations\Repositories\ConversationRepository), Object(App\Messages\Repositories\MessageRepository))
#17 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#18 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#19 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#20 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#21 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#22 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Triggers\Jobs\Infusionsoft\InfusionsoftSendTrigger))
#23 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Triggers\Jobs\Infusionsoft\InfusionsoftSendTrigger))
#24 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Triggers\Jobs\Infusionsoft\InfusionsoftSendTrigger), false)
#26 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#27 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#28 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#29 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#30 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('redis', 'infusionsoft-th...', Object(Illuminate\Queue\WorkerOptions))
#31 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'infusionsoft-th...')
#32 /var/www/app/releases/20190603161859/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#33 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#34 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#35 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#36 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#37 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#38 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#39 /var/www/app/releases/20190603161859/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#40 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#41 /var/www/app/releases/20190603161859/vendor/symfony/console/Application.php(901): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/app/releases/20190603161859/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/app/releases/20190603161859/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /var/www/app/releases/20190603161859/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 {main}

Next Infusionsoft\Http\HttpException: An HTTP error occurred: Unauthorized in /var/www/app/releases/20190603161859/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php:34
Stack trace:
#0 /var/www/app/releases/20190603161859/vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php(456): Infusionsoft\Http\InfusionsoftSerializer->request('ContactService....', 'https://api.inf...', Array, Object(fXmlRpc\Client))
#1 /var/www/app/releases/20190603161859/vendor/infusionsoft/php-sdk/src/Infusionsoft/Api/ContactService.php(73): Infusionsoft\Infusionsoft->request('ContactService....', '446523', Array)
#2 /var/www/app/releases/20190603161859/app/Integrations/Drivers/Infusionsoft.php(135): Infusionsoft\Api\ContactService->load('446523', Array)
#3 /var/www/app/releases/20190603161859/app/Integrations/Integration.php(331): App\Integrations\Drivers\Infusionsoft->App\Integrations\Drivers\{closure}()
#4 /var/www/app/releases/20190603161859/app/Integrations/Drivers/Infusionsoft.php(136): App\Integrations\Integration->try(Object(Closure))
#5 /var/www/app/releases/20190603161859/app/Triggers/Jobs/Infusionsoft/InfusionsoftSendTrigger.php(79): App\Integrations\Drivers\Infusionsoft->getContactDetails('446523')
#6 /var/www/app/releases/20190603161859/app/Triggers/Jobs/Infusionsoft/InfusionsoftSendTrigger.php(52): App\Triggers\Jobs\Infusionsoft\InfusionsoftSendTrigger->getContactDetailsForTrigger(Object(App\Triggers\Trigger), Object(Illuminate\Support\Collection))
#7 /var/www/app/releases/20190603161859/app/Triggers/Jobs/SendTrigger.php(158): App\Triggers\Jobs\Infusionsoft\InfusionsoftSendTrigger->mapContactDetails(Object(App\Triggers\Trigger), Object(Illuminate\Support\Collection))
#8 /var/www/app/releases/20190603161859/app/Triggers/Jobs/SendTrigger.php(129): App\Triggers\Jobs\SendTrigger->getContact(Object(App\Webhooks\Webhook), Object(Illuminate\Support\Collection))
#9 /var/www/app/releases/20190603161859/app/Triggers/Jobs/SendTrigger.php(117): App\Triggers\Jobs\SendTrigger->process()
#10 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiter.php(90): App\Triggers\Jobs\SendTrigger->App\Triggers\Jobs\{closure}()
#11 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiterBuilder.php(113): Illuminate\Redis\Limiters\DurationLimiter->block(3, Object(Closure))
#12 /var/www/app/releases/20190603161859/app/Triggers/Jobs/SendTrigger.php(120): Illuminate\Redis\Limiters\DurationLimiterBuilder->then(Object(Closure), Object(Closure))
#13 [internal function]: App\Triggers\Jobs\SendTrigger->handle(Object(App\Contacts\Repositories\ContactRepository), Object(App\Conversations\Repositories\ConversationRepository), Object(App\Messages\Repositories\MessageRepository))
#14 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#17 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#18 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#19 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Triggers\Jobs\Infusionsoft\InfusionsoftSendTrigger))
#20 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Triggers\Jobs\Infusionsoft\InfusionsoftSendTrigger))
#21 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Triggers\Jobs\Infusionsoft\InfusionsoftSendTrigger), false)
#23 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#24 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#25 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#26 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#27 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('redis', 'infusionsoft-th...', Object(Illuminate\Queue\WorkerOptions))
#28 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'infusionsoft-th...')
#29 /var/www/app/releases/20190603161859/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#30 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#31 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#32 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#33 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#34 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#35 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#36 /var/www/app/releases/20190603161859/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#37 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#38 /var/www/app/releases/20190603161859/vendor/symfony/console/Application.php(901): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /var/www/app/releases/20190603161859/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/app/releases/20190603161859/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/app/releases/20190603161859/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/app/releases/20190603161859/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 {main}
```

**Comment by ellisio** [comment]
Here is a grid of the timestamps for the log export for easier reading. It'll show you the 15 minute pattern that I'm talking about.

https://gist.github.com/ellisio/99d5e2fc67fe4333c97e8a1e54039be3

**Comment by brumiser1550** [comment]
I might have some data to contribute to this discussion as well, just have to figure out what client it happened to.

@ellisio you can set a logger on the Infusionsoft object when you instance it and it will dump everything (headers, requests, and responses) out to a log file.

```
    $ifs_logger = new Logger('client');
    $ifs_logger->pushHandler(new StreamHandler(__DIR__ . '/infusionsoft.log'));
    $infusionsoft = new Infusionsoft(array(
        'clientId' => IFS_CLIENT_KEY,
        'clientSecret' => IFS_CLIENT_SECRET,
        'redirectUri' => IFS_REDIRECT_URL,
    ));
    $infusionsoft->setHttpLogAdapter($ifs_logger);
    $infusionsoft->setDebug(true);
```
or if you don't use Monolog you can just set 
```
    $infusionsoft = new Infusionsoft(array(
        'clientId' => IFS_CLIENT_KEY,
        'clientSecret' => IFS_CLIENT_SECRET,
        'redirectUri' => IFS_REDIRECT_URL,
    ));
    $infusionsoft->setDebug(true);
    //some code....
    $logs = $infusionsoft->getLogs(); //is an array of logs with all the same info
```

**Comment by ellisio** [comment]
@brumiser1550 Awesome, thank you!

I'll test locally to see if I can attach the Laravel logger to the Infusionsoft client. We don't have large enough disks on our servers to persist log files if they get too large. We send logs to the syslog and let Google Cloud Logging aggregate the logs.

I'm assuming I can do something along the lines of the following:

```
$infusionsoft = new Infusionsoft($options);
$infusionsoft->setHttpLogAdapter(log());
$infusionsoft->setDebug(true);
```

Once I confirm that works, and I capture some logs with the headers, I'll report back here with the responses.

**Comment by bbooth** [comment]
Sounds good.  On failure we should see headers that start with `x-mashery`.  Those will have the information from mashery on why the think the request is bad.

**Comment by ellisio** [comment]
@bbooth Due to your logging trick we were able to identify the root cause. However, I still think there is something off on Mashery/Infusionsoft's side.

We had a customer get this error at 09:00:11 AM this morning. Once again, at the top of the hour. However, the underlying root cause of this issue is as follows on our end:

1. We were locking our queued jobs if a refresh was required for 10 seconds.
2. At the top of the hour, something happens on Mashery/Infusionsoft that causes the requests to take longer than 10 seconds at times.
3. This caused Job B to consume the lock and do a refresh of it's own. During that refresh on Job B, Job A finished, and a race condition occurred causing Job B to now have an invalid token.

After taking a big step back and looking at this, it became very clear that this is a problematic implementation on our end as a freight train of requests for a particular customer would come to a grinding halt once every 24 hours; with a high risk of failing the refresh request.

Our fix that we are implementing now is to have a CRON that runs at the top of the hour, every one, to grab tokens expiring in the next hour. Then dump those credentials into a queue to refresh each token one by one.

We understand there is still a small race condition that this might cause a queued job here and there to fail as the refresh for a token may happen at the same time a queued job is making a request using the old token; however this is our first step into stabilizing this issue on our end.

So, back to @ROMzombie's post above, this seems to be the case after all is said and done. Just very odd this race condition only happened at 15 minute markers throughout the hour.

Anywho, I really appreciate the help from everyone here and I consider this issue resolved. I think this kind of scenario makes for a good blog post to help others fully understand how this kind of setup works and some ways to ensure you don't shoot yourself in the foot when building high volume applications. 🍻

**Comment by bbooth** [comment]
Glad you got it squared away.  Ping me if you run into anything else.
