### ISSUE TITLE
Refresh Token is always Unauthorized.

### ISSUE THREAD

**Issue by manu144x** [infusionsoft/infusionsoft-php#91]
Hello, there seems to be an issue because I could not refresh the token the normal way not even once.
I always get this response: Unauthorized. I always have to re-authorize the initial token, after that it works perfectly fine.

What I do is very basic:
I serialize the Token object and I save it to a text file because it's a global thing. 

When I need to push data to Infusionsoft, I check if it's expired, and if it's not I just push it and works perfectly.

I am attaching the function because it's fairly self explanatory. Am I missing something?
Thank you.

```
/**
     * This function sets up the connection to Infusionsoft using Oauth2
     * @return Infusionsoft Object
     */
    public function setUpInfusionsoftConnection() {
        //Setting up the Infusionsoft object with the app id and secret configuration
        $infusionsoft = new Infusionsoft([
            'clientId' => \Config::get('services.infusionsoft.client_id'),
            'clientSecret' => \Config::get('services.infusionsoft.client_secret'),
            'redirectUri' => \Config::get('services.infusionsoft.redirect')
        ]);

        //we load the token we currently have from the file, and deserialize it.
        $tokenUnserialized = unserialize(file_get_contents(storage_path('infusionsoft-serialized-token.txt')));

        //of course, if we use it directly no method will work, but the properties can still be accessed so we are using that to create a new token object
        $tokenOptions = [
            'access_token' => $tokenUnserialized->accessToken,
            'refresh_token' => $tokenUnserialized->refreshToken,
            'expires_in' => $tokenUnserialized->endOfLife
        ];

        //we instantiate the infusionsoft token object with the options.
        $token = new \Infusionsoft\Token($tokenOptions);
        //we set the token
        $infusionsoft->setToken($token);


        //check for expiration, the token could be expired.
        if(time() > $token->endOfLife) {
            //yes it is expired, so we request an new token and (hopefully) we will use that one and move on with our lives.
            $token = $infusionsoft->refreshAccessToken();
            //we save the token to our file
            file_put_contents(storage_path('infusionsoft-serialized-token.txt'),serialize($token));
        }
        //we also set the infusionsoft object to use the new, fresh token object received.
        $infusionsoft->setToken($token);
        //we return it so we can do our dirty business.
        return $infusionsoft;
    }
```

**Comment by michaelekaufman** [comment]
I had the same issue. Don't set the 'expires_in' through the array. Set it directly after you create the Token.

```
        $tokenOptions = [
            'access_token' => $tokenUnserialized->accessToken,
            'refresh_token' => $tokenUnserialized->refreshToken,
        ];

        //we instantiate the infusionsoft token object with the options.
        $token = new \Infusionsoft\Token($tokenOptions);

        // set the endOfLife on the token with the full expiration date.
        $token->setEndOfLife($tokenUnserialized->endOfLife);

        //we set the token
        $infusionsoft->setToken($token);

        //check for expiration, the token could be expired.
        // infusionsoft's library has a function to check if the token is expired.
        if($infusionsoft->isTokenExpired()) {
            //yes it is expired, so we request an new token and (hopefully) we will use that one and move on with our lives.
            $token = $infusionsoft->refreshAccessToken();
            $infusionsoft->setToken($token);

            //we save the token to our file
            file_put_contents(storage_path('infusionsoft-serialized-token.txt'),serialize($token));
        }

        //we return it so we can do our dirty business.
        return $infusionsoft;
```

If you look at how Token is initialized during creation you will see that it adds the 'expires_in' duration to time(). Apparently when you receive back Token from Infusionsoft they only provide how long the token is good for, not when it expires. So when your manually creating the Token above it is actually setting the expiration to an incorrect value where the token will never think it is expired. 
To get around this, remove 'expires_in' from $tokenOptions and then you can just manually call setEndOfLife() after you create the Token.

I also add a couple other modifications, see if you can spot them.
Also, one thing worth noting. In my implementation I also included the 'token_type' and 'scope' inside my $tokenOptions.

Hope this helps.

**Comment by manu144x** [comment]
@michaelekaufman Thank you for your information, let's hope that is the actual issue.

The expiration is actually being detected properly for me, no issues there, but I will try doing it like you suggested and get back with information.

Thank you very much, you may have saved my life :)

**Comment by manu144x** [comment]
@michaelekaufman I implemented you changes, but unfortunately the response is the same. Always a bad request.

I even did it with Postman, a small app that I can use to replicate naked POST requests, and always the same. 

Also, if I try to refresh a token that is not expired yet, will it give me the same response, invalid refresh token?

It's just impossible to work with them, the API is extremely undocumented and unpredictable.

**Comment by manu144x** [comment]
@michaelekaufman If it's not too much to ask, can you post the code you have and if it's working?

Also where are you saving the token, in a database, in a file? Maybe that's what I'm doing wrong?

Thank you.

**Comment by kressaty** [comment]
In just about every scenario where someone is having an issue like this, either a) the token is not being serialized and stored properly, or b) there's an issue with your app credentials. Since you can get the initial access token in the first place, I'd say you should a) verify you can make any other request to the API with the access token you receive back, and b) make sure that if you're going to construct a new token (which we suggest you don't do, hence it not being in any example, tutorial, or documentation), it matches the Infusionsoft Token Object exactly.

**Comment by kressaty** [comment]
One more note - if you just run the example code provided in the library as is, and run it a few times so that it asks for a refresh token, does it work?

**Comment by manu144x** [comment]
@kressaty After the initial token is authorized, it works perfectly for 24 hours, I can access everything, it works perfectly fine.

I am suspecting the storing mechanism as well, I am trying now with the exact code from the example.

One quick question, if the token is not expired yet, can I refresh it anyway, or I have to wait until it actually expires? Because that way I can only debug every 24 hours. I tried to find documentation on this, but was not able to.

**Comment by kressaty** [comment]
Yep, you can refresh anytime (this is just a basic rule of OAuth spec, but you make a good point that we should call that out in the docs). The thing to remember when refreshing the token is that it gives you a completely new Access Token and Refresh Token, so when you do refresh, you'll update everything and use the new Access Token going forward.

**Comment by manu144x** [comment]
Yes, I am doing that exactly. 

What is your recommendation for storing the Token object, if I have to persist it across multiple sessions, so I can't store it in the Session like in the example? Serialize to database or file?

Thank you.

**Comment by kressaty** [comment]
I prefer the database, especially if you're using MySQL, since it can handle the text without messing with it and you don't have to worry about any filesystem issues. There's nothing wrong with storing it in a text file, I just find that it tends to open up the door for more PITA issues ;-).

**Comment by manu144x** [comment]
Understood, thank you very much for the reply. I will try to store it in the database, I will try also to use the barebones example in the github description and see what I come up with.

It may just be the file storage actually. 

Thank you very much.

**Comment by manu144x** [comment]
@kressaty Thank you for the replies, I just tried saving in the database, and the same issue.

So I went ahead and created a basic file with the example from your description, and it fails with the same error:

```
require_once '../vendor/autoload.php';

$infusionsoft = new \Infusionsoft\Infusionsoft(array(
    'clientId'     => 'a8fwggvahcb5hzr75q2kgn43',
    'clientSecret' => 'rFm9vehBnH',
    'redirectUri'  => 'http://pathwayone.dev.umisis.com/infusionsoft.php',
));

// If the serialized token is available in the session storage, we tell the SDK
// to use that token for subsequent requests.
if (isset($_SESSION['token'])) {
    $infusionsoft->setToken(unserialize($_SESSION['token']));
}

// If we are returning from Infusionsoft we need to exchange the code for an
// access token.
if (isset($_GET['code']) and !$infusionsoft->getToken()) {
    $token = $infusionsoft->requestAccessToken($_GET['code']);
}

if ($infusionsoft->getToken()) {
    // Save the serialized token to the current session for subsequent requests
    $_SESSION['token'] = serialize($infusionsoft->getToken());

    // MAKE INFUSIONSOFT REQUEST
    $newToken = $infusionsoft->refreshAccessToken();
    print_r($newToken);
} else {
    echo '<a href="' . $infusionsoft->getAuthorizationUrl() . '">Click here to authorize</a>';
}

```

The error is:
```
Fatal error: Uncaught exception 'Infusionsoft\Http\HttpException' with message 'exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.infusionsoft.com/token` resulted in a `400 Bad Request` response: {"error":"invalid_grant","error_description":"Authorization code is invalid"} ' in C:\Users\manu\Dropbox\PathwayOne\software\pathwayone\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:111 Stack trace: #0 C:\Users\manu\Dropbox\PathwayOne\software\pathwayone\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\Users\manu\Dropbox\PathwayOne\software\pathwayone\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\Users\manu\Dropbox\PathwayOne\software\pathwayone\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), in C:\Users\manu\Dropbox\PathwayOne\software\pathwayone\vendor\infusionsoft\php-sdk\src\Infusionsoft\Http\GuzzleHttpClient.php on line 73
```

Could it also be a Guzzle http client error?

**Comment by kressaty** [comment]
Please delete that immediately; you put your client ID and secret in.

**Comment by kressaty** [comment]
(That says your auth code is bad, which means the payload isn't being sent properly).

**Comment by manu144x** [comment]
@kressaty Just did it now, sorry, got carried away :)

**Comment by kressaty** [comment]
So this is a second issue - I'm guessing either a) you used the Auth Code a second time and it had expired, or b) since you're running Windows, perhaps it can't find the $_GET server var and you'll need to retrieve the code some other way.

**Comment by manu144x** [comment]
When I am doing it my way I have the same issue. 
Now saving in the database btw:

```
$infusionsoft = new Infusionsoft([
            'clientId' => \Config::get('services.infusionsoft.client_id'),
            'clientSecret' => \Config::get('services.infusionsoft.client_secret'),
            'redirectUri' => \Config::get('services.infusionsoft.redirect'),
        ]);

        $infusionsoft->setDebug(true);

        $oauthConfiguration = OauthConfiguration::where('provider','=','infusionsoft')->where('domain','=',$_SERVER['SERVER_NAME'])->get()->first();
        //dd($oauthConfiguration);
        if($oauthConfiguration) {
            $token = unserialize($oauthConfiguration->token_serialized);
        }

        $infusionsoft->setToken($token);
        $newToken = $infusionsoft->refreshAccessToken();
        $infusionsoft->setToken($newToken);
        //we save the token to the database
        $oauthConfiguration->update(['token_serialized' => serialize($newToken)]);
```
And the Token is identical to the one I receive from Infusionsoft in the callback url:
```
Token {#581 ▼
  +accessToken: "2vg886tz3u9run67g6qkrtnq"
  +refreshToken: "49vh353n54xwevzeu95mrufv"
  +endOfLife: 1480014883
  +extraInfo: array:2 [▼
    "token_type" => "bearer"
    "scope" => "full|uo115.infusionsoft.com"
  ]
}
```
It's a laravel dd(); dump of the object before I use it.

This is my development, the full server is an Ubuntu with nginx and HHVM. 
The interesting part is that I am running laravel/socialite with 4 other OAUTH2 setups and it works perfectly fine.

For infusionsoft of course I am using a custom callback where I am managing it:

```
public function handleInfusionsoftCallback(Request $request) {

        $scope = explode('|',$request->get('scope'));
        $scopeUrl = $scope[1];
        $scope = $scope[0];
        $code = $request->get('code');

        self::overloadSocialiteConfigurations();

        $infusionSoft = new Infusionsoft([
            'clientId' => \Config::get('services.infusionsoft.client_id'),
            'clientSecret' => \Config::get('services.infusionsoft.client_secret'),
            'redirectUri' => \Config::get('services.infusionsoft.redirect'),

        ]);
        $infusionSoft->requestAccessToken($code);
        $infusionSoftToken = $infusionSoft->getToken();




        if($infusionSoftToken) {
            $oauthConfiguration = OauthConfiguration::where('provider','=','infusionsoft')->where('domain','=',$_SERVER['SERVER_NAME'])->get()->first();
            // dd($infusionSoftToken);
            if($oauthConfiguration) {
                $oauthConfiguration->update(['token_serialized' => serialize($infusionSoftToken)]);
            }
            file_put_contents(storage_path('infusionsoft-serialized-token.txt'),serialize($infusionSoftToken));
        }
        return redirect(route('home'));

    }
```

It works perfectly fine on both Windows/Linux without any issues, except for refreshing the token.

I will try to see if I have the same issues on the Linux server.

Thank you so much for your patience so far. I am starting to suspect the GuzzleHTTP client is not working as it should and may be messing up something.

**Comment by manu144x** [comment]
I get the exact same error on linux:

```
exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.infusionsoft.com/token` resulted in a `400 Bad Request` response: ' in /vagrant/pathwayone/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111 Stack trace: #0 /vagrant/pathwayone/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create() #1 /vagrant/pathwayone/vendor/guzzlehttp/promises/src/Promise.php(203): Closure$GuzzleHttp\Middleware::httpErrors() #2 /vagrant/pathwayone/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler() #3 /vagrant/pathwayone/vendor/guzzlehttp/promises/src/TaskQueue.php(61): Closure$GuzzleHttp\Promise\Promise::settle() #4 /vagrant/pathwayone/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run() #5 /vagrant/pathwayone/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 /vagrant/pathwayone/vendor/guzzlehttp/promises/src/Promise.php(266): GuzzleHttp\Promise\Promise->waitIfPending() #7 /vagrant/pathwayone/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #8 /vagrant/pathwayone/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #9 /vagrant/pathwayone/vendor/guzzlehttp/guzzle/src/Client.php(104): GuzzleHttp\Promise\Promise->wait() #10 /vagrant/pathwayone/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/GuzzleHttpClient.php(67): GuzzleHttp\Client->send() #11 /vagrant/pathwayone/vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php(271): Infusionsoft\Http\GuzzleHttpClient->request() #12 /vagrant/pathwayone/app/User.php(261): Infusionsoft\Infusionsoft->refreshAccessToken() #13 /vagrant/pathwayone/app/Http/Controllers/OptInsController.php(188): App\User->refreshInfusionsoftToken() #14 (): App\Http\Controllers\OptInsController->refreshInfusionsoftToken() #15 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array() #16 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction() #17 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(95): Illuminate\Routing\ControllerDispatcher->call() #18 (): Closure$Illuminate\Routing\ControllerDispatcher::callWithinStack() #19 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func() #20 (): Closure$Illuminate\Routing\Pipeline::getInitialSlice() #21 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func() #22 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then() #23 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack() #24 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch() #25 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController() #26 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run() #27 (): Closure$Illuminate\Routing\Router::runRouteWithinStack() #28 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func() #29 /vagrant/pathwayone/vendor/pragmarx/tracker/src/Vendor/Laravel/Middlewares/Tracker.php(24): Closure$Illuminate\Routing\Pipeline::getInitialSlice() #30 (): PragmaRX\Tracker\Vendor\Laravel\Middlewares\Tracker->handle() #31 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array() #32 (): Closure$Illuminate\Pipeline\Pipeline::getSlice() #33 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func() #34 /vagrant/pathwayone/app/Http/Middleware/OptinsChecker.php(36): Closure$Illuminate\Routing\Pipeline::getSlice() #35 (): App\Http\Middleware\OptinsChecker->handle() #36 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array() #37 (): Closure$Illuminate\Pipeline\Pipeline::getSlice() #38 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func() #39 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Closure$Illuminate\Routing\Pipeline::getSlice() #40 (): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #41 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array() #42 (): Closure$Illuminate\Pipeline\Pipeline::getSlice() #43 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func() #44 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Closure$Illuminate\Routing\Pipeline::getSlice() #45 (): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #46 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array() #47 (): Closure$Illuminate\Pipeline\Pipeline::getSlice() #48 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func() #49 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Closure$Illuminate\Routing\Pipeline::getSlice() #50 (): Illuminate\Session\Middleware\StartSession->handle() #51 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array() #52 (): Closure$Illuminate\Pipeline\Pipeline::getSlice() #53 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func() #54 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Closure$Illuminate\Routing\Pipeline::getSlice() #55 (): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() #56 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array() #57 (): Closure$Illuminate\Pipeline\Pipeline::getSlice() #58 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func() #59 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Closure$Illuminate\Routing\Pipeline::getSlice() #60 (): Illuminate\Cookie\Middleware\EncryptCookies->handle() #61 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array() #62 (): Closure$Illuminate\Pipeline\Pipeline::getSlice() #63 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func() #64 (): Closure$Illuminate\Routing\Pipeline::getSlice() #65 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func() #66 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then() #67 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack() #68 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute() #69 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch() #70 (): Closure$Illuminate\Foundation\Http\Kernel::dispatchToRouter() #71 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func() #72 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Closure$Illuminate\Routing\Pipeline::getInitialSlice() #73 (): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() #74 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array() #75 (): Closure$Illuminate\Pipeline\Pipeline::getSlice() #76 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func() #77 (): Closure$Illuminate\Routing\Pipeline::getSlice() #78 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func() #79 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then() #80 /vagrant/pathwayone/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #81 /vagrant/pathwayone/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle() #82 {main} in file: /vagrant/pathwayone/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/GuzzleHttpClient.php on line: 73

```

I will try to see if I can obtain it manually by replicating an HTTP token request with Postman

**Comment by manu144x** [comment]
If I do it via postman, it seems to work:

![image](https://cloud.githubusercontent.com/assets/6595887/20576469/bc9c2120-b1c6-11e6-87e4-5e8563406c63.png)

I will try to create a custom RefreshToken method using curl or some other http client and see what happens.

Thank you.

**Comment by manu144x** [comment]
@kressaty I Finally got it to work.

I started debugging the http request, and it turns out it was sending the correct token, correct client_id and secret, but for some reason, it would have the wrong client_id and client_secret (totally my fault).

A rule of thumb for anyone else can be to make sure to debug the actual HTTP request before sending it to make sure it is what you expect, stupid me :)
